const INTERNAL_SERVER_ERROR_CODE = 500
const BAD_REQUEST_CODE = 400

const INCORRECT_PROTOCOL_MESSAGE = "Incorrect protocol!"

module.exports = {
    INTERNAL_SERVER_ERROR_CODE,
    BAD_REQUEST_CODE,
    INCORRECT_PROTOCOL_MESSAGE
}